# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 신은성
title: Software Engineer
email: eunsung.shin@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: watanka
instagram_username: eunsung.shin
linkedin_username: eun-sung-shin

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요, 머신러닝 엔지니어 신은성입니다. 인공지능 및 머신러닝 분야에서 주로 백엔드 서버 개발 및 배포를 맡고 있으며 다양한 AI 솔루션을 통해 비즈니스 문제를 해결해왔습니다.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: 콘서트 예약 시스템
        link: www.github.com/concert-reservation
        description: |
          대용량 트래픽을 처리하는 콘서트 티켓 예약 API를 개발했습니다.
          - 테스트 기반 코드 작성으로 지속 가능한 코드 유지
          - Redis의 Sorted Set과 JWT Token을 활용한 대기열 구현
          - Redisson 분산락을 적용하여 데이터 정합성 보장

  # - title: Experiences
  #   layout: split
  #   content:
  #     - layout: left-right
  #       left:
  #         title: 반려동물 진료비 예측 서비스 개발
  #         link: www.github.com/petpins
  #         description: |
  #           반려동물 보험 사이트에서 등록된 반려견 건강 정보를 바탕으로 진료비를 예측하는 시스템을 개발했습니다.
  #       right:
  #         description: |
  #           - 기존 보험청구 처리 시스템과 연동하여 AI 백엔드 서버 개발
  #           - 모델 학습 파이프라인 구성 및 최종 모델 정확도 90% 달성
  #           - nginx, docker, github action을 통한 무중단 배포 구현
      
  #     - layout: left-right
  #       left:
  #         title: 애자일소다
  #         sub_title: 머신러닝 엔지니어
  #         caption: 2020.07 - 2023.01
  #         link: www.github.com/petpins
  #         description: |
  #           B2B OCR 제품 개발 참여
  #       right:
  #         description: |
  #           - 일 6만건 이상의 문서 정보 자동화를 위한 텍스트 탐지 모델을 개발했습니다.
  #           - 텍스트 탐지 모델 정확도 93% 달성
  #           - Triton Inference Server로 서빙 효율 개선
  #           - 손글씨 인식률 4% 개선을 위한 semi-supervised learning 기법 적용
  #           - 손글씨 인식률 개선을 위한 데이터 수집 자동화
          
  #     - layout: left-right
  #       left:
  #         title: 애자일소다
  #         sub_title: 머신러닝 엔지니어 인턴
  #         caption: 2019.08 - 2020.02
  #         link: www.github.com/agilesoda
  #         description: |
  #           이미지 기반 사고 수리비 예측 프로젝트
  #       right:
  #         description: |
  #           - CNN 모델을 활용한 이미지 분류 모델 개발
  #           - 91% 정확도 달성

  - title: Education
    layout: list
    content:
      - layout: left
        title: Wasatch Academy
        caption: 2010 - 2013
        sub_title: 고등학교 졸업

      - layout: left
        title: Emory University
        caption: 2013 - 2019
        sub_title: 통계학/심리학 학사

  - title: Certificates
    layout: text
    content: |
      - **Certified Kubernetes Administrator (CNCF)** - 2023.05
      - **SQLD (한국데이터산업진흥원)** - 2022.10
      - **AWS Cloud Practitioner (AWS)** - 2021.12
      - **빅데이터 분석기사 (한국산업인력공단)** - 2022.07

  - title: ExtraCurricular
    layout: list
    content:
      - layout: left
        title: 글또 개발자 글쓰기 모임
        caption: 2022 - 현재
        description: |
          다양한 직군의 개발자들과 개발 관련 정보를 교류하고, 기술 블로그를 운영 중입니다.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
